# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"L\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x03 \x01(\x05\"\xb3\x01\n\x0eSearchResponse\x12.\n\x07results\x18\x01 \x03(\x0b\x32\x1d.search.SearchResponse.Result\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x10\n\x08has_next\x18\x03 \x01(\x08\x1aJ\n\x06Result\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\x0f\n\rStatusRequest\"I\n\x10\x44\x65pendencyStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05state\x18\x02 \x01(\x0e\x32\x18.search.OperationalState\"i\n\x0eStatusResponse\x12\'\n\x05state\x18\x01 \x01(\x0e\x32\x18.search.OperationalState\x12.\n\x0c\x64\x65pendencies\x18\x02 \x03(\x0b\x32\x18.search.DependencyStatus*w\n\x10OperationalState\x12\x1d\n\x19OPERATIONAL_STATE_UNKNOWN\x10\x00\x12!\n\x1dOPERATIONAL_STATE_OPERATIONAL\x10\x01\x12!\n\x1dOPERATIONAL_STATE_UNAVAILABLE\x10\x02\x32\x81\x01\n\rSearchService\x12\x37\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12\x37\n\x06Status\x12\x15.search.StatusRequest\x1a\x16.search.StatusResponseB\x18Z\x16./adapters/search/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026./adapters/search/grpc'
  _globals['_OPERATIONALSTATE']._serialized_start=483
  _globals['_OPERATIONALSTATE']._serialized_end=602
  _globals['_SEARCHREQUEST']._serialized_start=24
  _globals['_SEARCHREQUEST']._serialized_end=100
  _globals['_SEARCHRESPONSE']._serialized_start=103
  _globals['_SEARCHRESPONSE']._serialized_end=282
  _globals['_SEARCHRESPONSE_RESULT']._serialized_start=208
  _globals['_SEARCHRESPONSE_RESULT']._serialized_end=282
  _globals['_STATUSREQUEST']._serialized_start=284
  _globals['_STATUSREQUEST']._serialized_end=299
  _globals['_DEPENDENCYSTATUS']._serialized_start=301
  _globals['_DEPENDENCYSTATUS']._serialized_end=374
  _globals['_STATUSRESPONSE']._serialized_start=376
  _globals['_STATUSRESPONSE']._serialized_end=481
  _globals['_SEARCHSERVICE']._serialized_start=605
  _globals['_SEARCHSERVICE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
