# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/embed.EmbeddingService/Embed',
                request_serializer=embedding__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.EmbedQuery = channel.unary_unary(
                '/embed.EmbeddingService/EmbedQuery',
                request_serializer=embedding__pb2.QueryEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.QueryEmbeddingResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/embed.EmbeddingService/Status',
                request_serializer=embedding__pb2.EmbeddingStatusRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbeddingStatusResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request, context):
        """Chunks, embeds, and stores a crawled document.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedQuery(self, request, context):
        """Embeds a search query with the same model used for documents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Reports whether model inference is ready.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=embedding__pb2.EmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.EmbeddingResponse.SerializeToString,
            ),
            'EmbedQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedQuery,
                    request_deserializer=embedding__pb2.QueryEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.QueryEmbeddingResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=embedding__pb2.EmbeddingStatusRequest.FromString,
                    response_serializer=embedding__pb2.EmbeddingStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embed.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embed.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embed.EmbeddingService/Embed',
            embedding__pb2.EmbeddingRequest.SerializeToString,
            embedding__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embed.EmbeddingService/EmbedQuery',
            embedding__pb2.QueryEmbeddingRequest.SerializeToString,
            embedding__pb2.QueryEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embed.EmbeddingService/Status',
            embedding__pb2.EmbeddingStatusRequest.SerializeToString,
            embedding__pb2.EmbeddingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
