// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: embedding.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EmbeddingService_Embed_FullMethodName      = "/embed.EmbeddingService/Embed"
	EmbeddingService_EmbedQuery_FullMethodName = "/embed.EmbeddingService/EmbedQuery"
	EmbeddingService_Status_FullMethodName     = "/embed.EmbeddingService/Status"
)

// EmbeddingServiceClient is the client API for EmbeddingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbeddingServiceClient interface {
	// Chunks, embeds, and stores a crawled document.
	Embed(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	// Embeds a search query with the same model used for documents.
	EmbedQuery(ctx context.Context, in *QueryEmbeddingRequest, opts ...grpc.CallOption) (*QueryEmbeddingResponse, error)
	// Reports whether model inference is ready.
	Status(ctx context.Context, in *EmbeddingStatusRequest, opts ...grpc.CallOption) (*EmbeddingStatusResponse, error)
}

type embeddingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingServiceClient(cc grpc.ClientConnInterface) EmbeddingServiceClient {
	return &embeddingServiceClient{cc}
}

func (c *embeddingServiceClient) Embed(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, EmbeddingService_Embed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingServiceClient) EmbedQuery(ctx context.Context, in *QueryEmbeddingRequest, opts ...grpc.CallOption) (*QueryEmbeddingResponse, error) {
	out := new(QueryEmbeddingResponse)
	err := c.cc.Invoke(ctx, EmbeddingService_EmbedQuery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingServiceClient) Status(ctx context.Context, in *EmbeddingStatusRequest, opts ...grpc.CallOption) (*EmbeddingStatusResponse, error) {
	out := new(EmbeddingStatusResponse)
	err := c.cc.Invoke(ctx, EmbeddingService_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingServiceServer is the server API for EmbeddingService service.
// All implementations must embed UnimplementedEmbeddingServiceServer
// for forward compatibility
type EmbeddingServiceServer interface {
	// Chunks, embeds, and stores a crawled document.
	Embed(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	// Embeds a search query with the same model used for documents.
	EmbedQuery(context.Context, *QueryEmbeddingRequest) (*QueryEmbeddingResponse, error)
	// Reports whether model inference is ready.
	Status(context.Context, *EmbeddingStatusRequest) (*EmbeddingStatusResponse, error)
	mustEmbedUnimplementedEmbeddingServiceServer()
}

// UnimplementedEmbeddingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmbeddingServiceServer struct {
}

func (UnimplementedEmbeddingServiceServer) Embed(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedEmbeddingServiceServer) EmbedQuery(context.Context, *QueryEmbeddingRequest) (*QueryEmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmbedQuery not implemented")
}
func (UnimplementedEmbeddingServiceServer) Status(context.Context, *EmbeddingStatusRequest) (*EmbeddingStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEmbeddingServiceServer) mustEmbedUnimplementedEmbeddingServiceServer() {}

// UnsafeEmbeddingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingServiceServer will
// result in compilation errors.
type UnsafeEmbeddingServiceServer interface {
	mustEmbedUnimplementedEmbeddingServiceServer()
}

func RegisterEmbeddingServiceServer(s grpc.ServiceRegistrar, srv EmbeddingServiceServer) {
	s.RegisterService(&EmbeddingService_ServiceDesc, srv)
}

func _EmbeddingService_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingServiceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingService_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingServiceServer).Embed(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingService_EmbedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingServiceServer).EmbedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingService_EmbedQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingServiceServer).EmbedQuery(ctx, req.(*QueryEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingServiceServer).Status(ctx, req.(*EmbeddingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingService_ServiceDesc is the grpc.ServiceDesc for EmbeddingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "embed.EmbeddingService",
	HandlerType: (*EmbeddingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _EmbeddingService_Embed_Handler,
		},
		{
			MethodName: "EmbedQuery",
			Handler:    _EmbeddingService_EmbedQuery_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _EmbeddingService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "embedding.proto",
}
